# Flask
DEBUG = True
SECRET_KEY = ''

# Twitter
TWITTER_BOT_HANDLE = ''
TWITTER_CONSUMER_CALLBACK = ''
TWITTER_CONSUMER_KEY = ''
TWITTER_CONSUMER_SECRET = ''
TWITTER_ACCESS_TOKEN = ''
TWITTER_ACCESS_TOKEN_SECRET = ''
